name: Run Tests and send coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Test with Maven
      run: mvn clean test
    - name: Upload coverage information to codacy
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: target/site/jacoco/jacoco.xml
        
